apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::062457645135:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-UEBEU2LEXB3N
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::062457645135:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-29T23:08:35Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1553"
  uid: 3ab4ef61-2a2c-47ae-b122-fd01305a8051
